// <auto-generated />
using System;
using ECommerce.WebAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.WebAPI.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    partial class ECommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.WebAPI.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c80e56c7-0a0a-40a8-b30a-763e5e8da53b"),
                            CreatedDate = new DateTime(2024, 5, 8, 17, 9, 30, 860, DateTimeKind.Local).AddTicks(5352),
                            Email = "admin@admin.com",
                            FirstName = "Admin",
                            LastName = "Admin",
                            Password = "1234"
                        });
                });

            modelBuilder.Entity("ECommerce.WebAPI.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cedc9f23-3d24-40b0-834a-00d3e992df26"),
                            CreatedDate = new DateTime(2024, 5, 8, 17, 9, 30, 860, DateTimeKind.Local).AddTicks(7261),
                            Description = "Black Ballpoint Pen",
                            Name = "Black Ballpoint Pen",
                            Price = 5m
                        },
                        new
                        {
                            Id = new Guid("ee7d4f83-cb5f-48d9-bbe1-b8cfd4d8d929"),
                            CreatedDate = new DateTime(2024, 5, 8, 17, 9, 30, 860, DateTimeKind.Local).AddTicks(7284),
                            Description = "Blue Ballpoint Pen",
                            Name = "Blue Ballpoint Pen",
                            Price = 6m
                        },
                        new
                        {
                            Id = new Guid("e8cdf575-4e49-4ed7-a3ea-3c7b4f11cfbd"),
                            CreatedDate = new DateTime(2024, 5, 8, 17, 9, 30, 860, DateTimeKind.Local).AddTicks(7288),
                            Description = "Red Ballpoint Pen",
                            Name = "Red Ballpoint Pen",
                            Price = 7m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
